make_timeline.py

Explicitly silence compiler deprecation warnings that seem to come from django.db via kadi.events in our environment.

Ignore compiler deprecation warnings

---

make_timeline.py

Ignore warnings like:
** ERROR - line 245: <<2015-Jun-14 08:01>> /proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/tables/conditions.py:419: DeprecationWarning: using `oa_ndim == 0` when `op_axes` is NULL is deprecated. Use `oa_ndim == -1` or the MultiNew iterator for NumPy <1.8 compatibility

Ignore a specific numpy deprecation warning

---

NOTES.change_PR34
make_timeline.py

Wrap ACE p3 fluence calc and plot in a try/except .
The try/except with print statement should let make_timeline finish and plot other useful values instead of dying on bad/missing "live" p3 data.
```
File "/proj/sot/ska/share/arc/make_timeline.py", line 412, in main
args.min_flux_samples, args.max_slope_samples)
File "/proj/sot/ska/share/arc/calc_fluence_dist.py", line 62, in get_fluence_percentiles
fl10, fl50, fl90 = np.percentile(fluences, [10, 50, 90], axis=0)
...
IndexError: cannot do a non-empty take from an empty axes.
```

Wrap ACE p3 fluence calc and plot in a try/except

---

arc.pl
make_timeline.py
task_schedule.cfg

Keep the timeline working without hrc data
This is a super-simple edit that puts in two dummy points of hrc data if there is nothing in the hrc_shield.h5 file.
The edit also just comments out the parts of task schedule intended to update the hrc proxy data file.
I've run this in a dev ska to show it completes.

Keep the timeline working without hrc data

---

arc.pl

Update version to 4.2.0
Oops.  I'd push this to master without review and installed arc, but forgot to push to github.  Will need new increment for the GOES proton data anyway.

Update version to 4.2.0

---

get_goes_x.py

Tweak print error (for accuracy and to not match "failed")
We updated this line to strip the Warning, hoping not to match the watch_cron_logs.  But there's also a search for "failed" in the arc watch_cron_logs and I think we want to keep that to match various Perl fails, so let's tweak this printed warning again.

Tweak print error (for accuracy and to not match "failed")

---

Makefile
get_iFOT_events.pl
get_web_content.pl
iFOT_queries.cfg
web_content.cfg

Set to use Net::Netrc for credentials for get_iFOT_events and get_web_content occweb queries.
Also remove a broken DATA install in the Makefile and comment out installation of DATA from the Makefile.
Functional testing:
Copied appropriate credentials to kadi user .netrc and ran get_iFOT_events and get_web_content without credential errors.

Set to use Net::Netrc for credentials

---

get_hrc.py

Mark missing proton channel data as -100000.0 instead of exiting
For the individual channel data, instead of a sys.exit if there is a missing entry for one or more of the channels for one of the times, this code creates the new time column and list of new records as the unique times in the new data, and indexes into those times with the channel data (setting any missing per-channel data to -100000.0 which seemed to be the convention).
If there is p5, p7, or p9 data that is negative, the row will be ignored for hrc by the other filtering (if I understand this correctly).
Fixes #57

Mark missing proton channel data as -100000.0 instead of exiting

---

alert_limits.html

This PR addresses Issue #41 and updates information in alert_limits.html.
- remove E150, E1300
- MCP A, replace with MCP B
- SHIELD A, replace with SHIELD B
- P4GM (GOES P2 * 3.3), replace with P4GM (GOES P4 * 3.3) (GOES-16 P4 roughly corresponds to the 'old' GOES P2 channel) 
- P4GM (GOES P5 * 12), replace with P4GM (GOES P7 * 12) (GOES-16 P7 roughly corresponds to the 'old' GOES P5 channel)
- ACE 130-214 keV, replace with 115-195 keV (current energies of the ACE P3 channel used for alerting)
Hopefully, this update can be included in the Replan Central installation following the ska3-shiny upgrade.
Not sure how to update the time tag and contact info - direct edit?

Updated alert limits html page

---

arc.pl
arc3.cfg

Use netrc for arc.pl occweb credentials.
#56 did this for get_iFOT_events and get_web_content, but didn't do this last one.
This is tested via a kadi user account and a test setup per the wiki.

Use netrc for arc.pl occweb credentials

---

arc.pl

Stop fetching and parsing thermal constraint file.
The thermal constraint file is no longer created by FOT thermal as the outputs are no longer relevant / no longer based on models used by the FOT.  The file used to be included in the FOT approved products outputs.  
- [n/a] Passes unit tests - unit tests have not been modernized and are presently disabled in Replan Central.
In a test version (see [wiki](https://github.com/sot/arc/wiki/Set-up-test-Replan-Central) for howto) this PR removed the warning "Could not find constraints file for any load version of therm_JAN1022" from the top and the load link was appropriately populated with the link to the approved JAN1022A directory.

Stop fetching and parsing thermal constraint file

---

make_timeline.py

Fix bug in plot_multi_line which occurs when there are no grating state changes over the timeline time interval.
None
The current kadi states look to not have the issue (no gratings) that seems to bring this up.  I just set "z" (the grating state) to be all zeros and confirmed old code gives this error:
```
File "/fido.real/kadi/arc3_test/lib/python3.8/site-packages/matplotlib/cm.py", line 455, in to_rgba
x = self.norm(x)
File "/fido.real/kadi/arc3_test/lib/python3.8/site-packages/matplotlib/colors.py", line 1801, in __call__
iret = np.digitize(xx, self.boundaries) - 1 + self._offset
File "<__array_function__ internals>", line 5, in digitize
File "/fido.real/kadi/arc3_test/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4852, in digitize
raise ValueError("bins must be …
```

Fix bug in plot_multi_line for no grating state changes

---

get_goes_x.py

Remove short and long warning that we're not using.
We aren't doing anything with the warning anyway, so it is just noise.  Originally there was the expectation that the data might be corrupted if the tables had mismatched lengths.  If that is happening, it doesn't seem to be having any impact.

Remove short and long warning that we're not using

---

web_content.cfg

Try more times for solar_wind png and increase warn delay.
I'm hoping this reduces instances of 
```
Warning: 500 Can't connect to space.umd.edu:443 (Connection reset by peer) for web data solar_wind (https://space.umd.edu/pm/)
```

Try more times for solar_wind png and increase warn delay

---

make_timeline.py

Update deprecation warning type for ska3-prime
Without this fix we get
```
/proj/sot/ska3/test/share/arc3/make_timeline.py:36: MatplotlibDeprecationWarning: mplDeprecation was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use matplotlib.MatplotlibDeprecationWarning instead.
category=matplotlib.cbook.mplDeprecation)
```
I tested this and with the fix we don't get that warning.

Update deprecation warning type for ska3-prime

---

get_ace.py

Update get_ace to use format instead of Reader
This should stop all of the speedy-astropy warnings in the logs like
```
############################################################
/proj/sot/ska3/flight/share/arc3/get_ace.py --h5=/proj/sot/ska3/flight/data/arc3/ACE.h5
############################################################
<<2024-Mar-21 06:06>> WARNING: AstropyDeprecationWarning: "Reader" was deprecated in version 6.0 and will be removed in a future version.
<<2024-Mar-21 06:06>> Use "format" instead. [__main__]
```
I confirmed format and Reader gave the same table
format
```
year month dom hhmm  mjd   secs destat  de1   de4  pstat   p1    p3   p5   p6    p7  anis_idx
---- ----- --- ---- ----- ----- ------ ------ ---- ----- ------ ---- ---- ---- ----- --------
2024     3  22 1850 …
```

Update get_ace to use format instead of Reader

---

make_timeline.py
pyrightconfig.json
utils/convert_states_to_yaml.py
utils/get_date_now.py

This improves the code structure for `make_timeline.py` and establishes a process for testing.
Highlights:
- Detailed test process with a couple of new utility scripts to help.
- Use dynamic file paths instead of hardwired global paths at import time.
- In "flight" mode (without `--test`), input data file paths are hardwired to various paths available on HEAD
- In "test" mode (with `--test`), input data files must all be in the directory defined by `--data-dir` (default `t_now`).
- Make module importable without side-effects.
- Add a function to grab some files from the web for testing and put them in the `--data-dir` directory.
- Use CxoTime instead of DateTime.
- Refactor `main()` into smaller drawing functions. This addresses a longstanding TODO, made easy now with VS code.
None …

Refactor and improve timeline testing infrastructure

---

arc.pl
make_timeline.py

FOT MP maintains a table of "available comms", which means intervals when DSN stations are in view of Chandra and are not currently scheduled for another mission. This means they could likely be used by Chandra if needed.
This update to Replan Central uses that table of available comms to annotate the timeline plot accordingly. This will help with planning anomaly recovery efforts. This adds two new elements:
- A grey timeline strip to the bottom of the timeline plot and the text annotation `Avail comms` to the bottom right.
- A new table of available comms below the table of timeline status data. This table is hidden by default and can be toggled on/off with a button click.
Example output is at: https://cxc.cfa.harvard.edu/mta/ASPECT/tests/arc/pr87/arc3/
The Replan Central HTML and …

Add available comms to timeline plot

---

get_solar_flare_png.py

Add requests checking and retry to solar flare fetch
Fixes issue/bug in https://github.com/sot/arc/pull/90 that a failed fetch will create a cached "image" file that is the http error response like
```
jeanconn-fido> more AR_CH_20250302.png 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>404 Not Found</title>
<style type="text/css"></style>
</head>
<body>
<div align="center">
<h2><span class="style3">404 Not Found</span></h2>
<table border="0" cellpadding="8" cellspacing="0" width="460">
<tbody><tr><td class="s">The requested URL was not found on this server.</td></tr></tbody>
</table>
</div>
</body>
</html>
```
I locally edited the script to change the value of img_url to a non-existent remote file, and confirmed that
1. the previously …

Add requests checking and retry to solar flare fetch

---

get_solar_flare_png.py

Use copyfile not copy
The update script is run by multiple users, so copy() runs into issues with chmod and spits these into the log:
```
<<2025-Mar-24 06:11>> Traceback (most recent call last):
<<2025-Mar-24 06:11>> File "/proj/sot/ska3/flight/share/arc3/get_solar_flare_png.py", line 116, in
<<2025-Mar-24 06:11>> main()
<<2025-Mar-24 06:11>> File "/proj/sot/ska3/flight/share/arc3/get_solar_flare_png.py", line 111, in main
<<2025-Mar-24 06:11>> shutil.copy(img_file, standard_image_path)
<<2025-Mar-24 06:11>> File "/proj/sot/ska3/flight/lib/python3.12/shutil.py", line 436, in copy
<<2025-Mar-24 06:11>> copymode(src, dst, follow_symlinks=follow_symlinks)
<<2025-Mar-24 06:11>> File "/proj/sot/ska3/flight/lib/python3.12/shutil.py", line 317, in copymode
<<2025-Mar-24 06:11>> chmod_func(dst, …
```

Set solar flare fetch code to use copyfile not copy when updating the file
